version: "3"
services:
    shell:
      image: tacc-svl-${MPI_ARCH}
      build:
        context: .
        dockerfile: tacc-svl-${MPI_ARCH}
      cap_add:
        - SYS_PTRACE
      stdin_open: true # docker run -i
      tty: true        # docker run -t
      volumes:
        - ./data:/home/svl/data

    test:
      image: tacc-svl-${MPI_ARCH}
      build:
        context: .
        dockerfile: tacc-svl-${MPI_ARCH}
      cap_add:
        - SYS_PTRACE
      volumes:
        - ./B04-DY_Lin_2D_Incline_DRM_PML_Boundary_Elastic_Quad4.py:/home/svl/B04-DY_Lin_2D_Incline_DRM_PML_Boundary_Elastic_Quad4.py
        - ./run_test_B04.sh:/home/svl/run_test_B04.sh
      entrypoint: /bin/bash run_test_B04.sh



